services:
  action:
    build:
      context: .
      dockerfile: docker/action/Dockerfile
  standalone:
    build:
      context: .
      dockerfile: docker/standalone/Dockerfile
    environment:
      INPUT_DATA_PATHS: /data
    image: kos-kit/explorer
    volumes:
      - ./data:/data:ro
